---
- name: Add a local user to Ubuntu
  hosts: all
  become: yes  # This makes sure Ansible runs the tasks with sudo privileges
  tasks:
    - name: Add a new user
      user:
        name: kranadmin        # Replace with the username you want to create
        state: present       # Ensure the user is present (i.e., created)
        shell: /bin/bash     # Set the shell for the user (optional)
        password: "{{ 'password123' | password_hash('sha512') }}"  # Set password (hashed)
        create_home: yes     # Ensure home directory is created
