---
- name: Add a new user to the system
  hosts: all  # You can specify specific hosts or a group of hosts here
  become: true  # This ensures the task is run with sudo (admin) privileges
  vars:
    ansible_python_interpreter: /usr/libexec/platform-python
  tasks:
    - name: Create a new user
      user:
        name: "kranadmin"   # The username can be passed as a variable
        state: present           # Ensures the user is present (created)
        shell: /bin/bash         # Specify default shell for the user
        create_home: yes         # Creates the user's home directory
        comment: "New User"      # Optional: adds a comment/description

